name: Update template

permissions:
  contents: write

on:
  repository_dispatch:
    types: [update-template]

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ensures repo checkout uses the token

      - name: Setup Git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Clean directory files/folders
        run: bun run scripts/clean-old-files.ts

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run artifact fetcher
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_TOKEN: ${{ secrets.ARTIFACT_TOKEN }}
          ARTIFACT_NAME: ${{ github.event.client_payload.artifactName }}
          RUN_ID: ${{ github.event.client_payload.runId }}
          REPO_OWNER: ${{ github.event.client_payload.repoOwner }}
          REPO_NAME: ${{ github.event.client_payload.repoName }}
        run: bun run scripts/fetchArtifact.ts

      - name: Update template
        run: bun run scripts/applyFiles.ts

      - name: Cleanup unnecessary files
        run: bun run scripts/cleanUp.ts

      - name: Workflow callback
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_TOKEN: ${{ secrets.ARTIFACT_TOKEN }}
          RUN_ID: ${{ github.event.client_payload.runId }}
          REPO_OWNER: ${{ github.event.client_payload.repoOwner }}
          REPO_NAME: ${{ github.event.client_payload.repoName }}
        run: bun run scripts/deleteArtifact.ts

      - name: Commit changes
        run: |
          git add .
          git commit -m "Apply incoming file updates" || echo "No changes to commit"

      - name: Force push to branch
        run: |
          git push origin HEAD:main --force
